version: '3.8'

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: app
      MYSQL_USER: root
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: passwd

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  # recette-api:
  #   build:
  #     context: ./recette-api
  #     dockerfile: ../docker/Dockerfile
  #   container_name: recette-container
  #   restart: unless-stopped
  #   volumes:
  #     - ./recette-api:/api
  #   ports:
  #     - 4002:4000

  # grpc-api:
  #   build:
  #     context: ./grpc-api
  #     dockerfile: ../docker/Dockerfile
  #   container_name: api-container
  #   restart: unless-stopped
  #   volumes:
  #     - ./grpc-api:/api
  #     - ./grpc-shared-protos:/grpc-shared-protos
  #   ports:
  #     - 5001:5050

  grpc-recette-service:
    build:
      context: ./grpc-recette-service
      dockerfile: ../docker/Dockerfile
    container_name: grpc-recette-service-container
    restart: unless-stopped
    volumes:
      - ./grpc-recette-service:/api
      - ./grpc-shared-protos:/grpc-shared-protos
    ports:
      - 5002:5060
